### ISSUE TITLE
Project Abandoned?

### ISSUE THREAD

**Issue by GarethSomers** [ErickTamayo/laravel-scout-elastic#136]
Hi @ErickTamayo are you still maintaining this project?

**Comment by babatundestickee** [comment]
Interesting i was going to ask the same question @GarethSomers

**Comment by prialgauskaslt** [comment]
For those who are looking for easy drop-in replacement for this package which works:
`composer require prialgauskaslt/laravel-scout-elastic`
I have added per-model indicing and plan on maintaining my fork for the upcoming years to come.
Ping me at my fork with issue linking PR in this repo which you think I should merge in new fork. 
Cheers!

**Comment by amsoell** [comment]
@prialgauskaslt You don't have issues enabled on your fork, otherwise I would post there. Your fork isn't Scout 8 compatible, so it isn't Laravel 7 compatible. Can you update the composer.json file to `^5.0|^6.0|^7.0|^8.0`?

**Comment by mallardduck** [comment]
@prialgauskaslt Can you open your projects Issue tracker up? I started using your fork due to what you said here:
> plan on maintaining my fork for the upcoming years to come.

So far so good - except I just hit my first main "issue" which is working with authenticated ES instances. So I'd like to open an issue about adding authentication to the library.

**UPDATE:** After further reading of docs I realized I overlooked the good ol' HTTP url encoded auth. So "adding" authentication via API may be interesting, but is not strictly required at all. Users can simply use:

```
http://user:pass@127.0.0.1:9200
```

**Comment by ErickTamayo** [comment]
hey, @prialgauskaslt if you like I can add you as a maintainer/collaborator if you want. I'm really sorry as I haven't had time to give this library the maintenance it needs.

**Comment by prialgauskaslt** [comment]
Hey! @ErickTamayo , yeah, it would be great if I could help maintaining it. I need this library every day so it seems that for a few good years I will give it my love

**Comment by benmag** [comment]
I've temporary switched to this fork I found: https://github.com/Betalabs/laravel-scout-elastic as a drop in replacement since it's compatible with Laravel 7 & Scout 8 

```
composer require betalabs/laravel-scout-elastic
```

@prialgauskaslt if you do become a maintainer and can add (or accept a PR for) Laravel 7 support, please ping me. Would love to switch back to the original repo

**Comment by ErickTamayo** [comment]
@prialgauskaslt is added as a collaborator, maybe we can discuss updating the library with your fork?

**Comment by mallardduck** [comment]
@benmag - it looks like @prialgauskaslt was added as they have a "Collaborator" badge now. So I think they should be able to merge PRs and handle publishing new releases now.

**Comment by ErickTamayo** [comment]
I'll be releasing v8 tomorrow or Monday for Laravel 8. I will probably release another one compatible with L7 after that
