### ISSUE TITLE
ElasticsearchEngine doesn't care about Builder::$index

### ISSUE THREAD

**Issue by Dadibom** [ErickTamayo/laravel-scout-elastic#31]
ElasticsearchEngine uses $this->index instead of $builder->index, which makes it impossible to search in different indices. It looks like $builder->index is null if you don't set it to something using the within-function, so you could probably just use this:

`
'index' => $builder->index ?: $this->index,
`

**Comment by ErickTamayo** [comment]
Right now we use different types of documents in the same index (specified in the scout config).

I agree that for searching with `within()` method is not handling the types correctly and will be fixed in an upcoming update.

As for having different indices for each model I probably will come with something as well.
