### ISSUE TITLE
Scout orderBy() not supported

### ISSUE THREAD

**Issue by denudge** [ErickTamayo/laravel-scout-elastic#86]
The function orderBy() on the Scout query builder has no effect here (or is buggy).

**Comment by kronthto** [comment]
Can you provide an example of what you tried?

I have an application where I'm using `->orderBy('created_at', 'desc')` and it is working just fine. In my case the value of this field is an `integer`; I think if you want to order by a `date` or another non-int type you'll have declare what the field contains in the Elastic index by adding a mapping: https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-put-mapping.html / https://github.com/ErickTamayo/laravel-scout-elastic/issues/47#issuecomment-290853108

**Comment by denudge** [comment]
In my case, I used two simple text fields (name, description). I did not create any special mapping beforehand.
ES has the following:
"name": {
  "type": "text",
  "fields": {
    "keyword": {
      "type": "keyword",
      "ignore_above": 256
    }
  }
}

Then, orderBy('name') didn't work.

**Comment by kronthto** [comment]
I just tried adding a sort on a text field (`asset_name` in my case) and actually got this error from Elastic: 
_Fielddata is disabled on text fields by default. Set fielddata=true on [asset_name] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead._

Following this error message I tried changing it to the following (add `.keyword`):
``` php
->orderBy('asset_name.keyword')
```
And it worked, I got my result ordered alphabetically by this field.

Edit: Got the idea to add `.keyword` here: https://github.com/elastic/kibana/issues/6769#issuecomment-228771571

I don't feel like this is something that should be fixed in this project though, as we can't really know of what type the specified order-column is.

**Comment by denudge** [comment]
Thanks for the hint. Unfortunately adding ".keyword" didn't work out for me either. I will try it again later, when I have more time to track the issue down.

**Comment by sebastiansulinski** [comment]
I seem to have similar issue with Algolia implementation - here's my controller method:

```php
public function search(Request $request): JsonResponse
{
    $query = Agent::query();

    if (!is_null($keyword = $request->get('keyword'))) {
        $query = Agent::search($keyword);
    }

    if (!is_null($sort = $request->get('sort')) && !is_null($direction = $request->get('direction'))) {
        $query->orderBy($sort, $direction === 'desc' ? 'desc' : 'asc');
    } else {
        $query->orderBy('firstname')->orderBy('lastname');
    }

    $agents = $query->paginate(10);

    return new JsonResponse($agents);
}
```

When I call with `keyword` empty - sorting works fine, but when I send the `keyword` through - `orderBy` method doesn't have any effect.

I have no default sorting set up on the algolia index for this searchable.

**Comment by marcoskubis** [comment]
@sebastiansulinski the orderBy doesn't have any effect because this piece of code:
https://github.com/ErickTamayo/laravel-scout-elastic/blob/master/src/ElasticsearchEngine.php#L224

```
...
return collect($results['hits']['hits'])->map(function ($hit) use ($model, $models) {
    return isset($models[$hit['_id']]) ? $models[$hit['_id']] : null;
})->filter()->values();
...
```
This code resets the collection's order and appears in all engines I have seen. And I dont know why it is needed.
