### ISSUE TITLE
Elasticsearch 6.0 update?

### ISSUE THREAD

**Issue by zanematthew** [ErickTamayo/laravel-scout-elastic#90]
Any plans to update this to support the breaking changes in 6.0?

**Comment by zanematthew** [comment]
FWIW, I forked this repo, and have it working with Elasticsearch 6.0. Overall it was just a matter of removing the references for `type`, since Elasticsearch no longer supports multiple types.

An eloquent approach would be to support index to model mappings. I believe this was mentioned in another repo issue.

**Comment by IllyaMoskvin** [comment]
Related: PRs #91 and #62. I think the issue you mentioned is #39.

Deprecating support for multiple types is a huge move that's gonna affect a lot of projects. This seems to be the de-facto Elasticsearch engine for Scout. It'd be good to address this issue soon, so as to prevent people from having to depend on their own forks.

One thing to note is that supporting the one-index-per-model paradigm does not _per se_ require dependence on Elasticsearch 6.0. Anecdotally, our team got it working for v.5.3, but I'm sure it could be implemented even earlier than that. Elasticsearch's own [roadmap](https://www.elastic.co/guide/en/elasticsearch/reference/6.0/removal-of-types.html#_schedule_for_removal_of_mapping_types) states that enabling explicit `single_type` mode is possible starting with v.5.6.0.

From that perspective, keeping the `"elasticsearch/elasticsearch": "^5.0"` dependency seems worthwhile. It also means that PHP 5 support won't need to be deprecated, and the Travis config won't need to be updated to roll out this change. It's also desirable from the ecosystem perspective, since as of this moment, AWS's ES offering supports a max version of 5.5.

Lastly, type support won't be 100% retired until v.9.0. I bring this up because supporting legacy installs that contain types could be a consideration well into v.6.0 and beyond. I'm down to ignore that if it means a faster update for this project, though.

**Comment by iraklisg** [comment]
@IllyaMoskvin good points 
> ...seems to be the de-facto Elasticsearch engine for Scout. It'd be good to address this issue soon, so as to prevent people from having to depend on their own forks.

Indeed, support for PHP5 can be done in a separate PR, since IMHO the _one index per document type_ alternative approach to deprecated _mapping types_ is well addressed both in #91 and #62 either using PHP5/PHP7 or elasticsearch5/elasticsearch6

**Comment by ghost** [comment]
Any news about this? I'm stuck with my ELK stack at 5.x.
Also, meanwhile there are some updated forks that work with 6.x?

**Comment by ErickTamayo** [comment]
Version 8.0 for Laravel 8 was just released. If you need support for a previous version, please open an issue requesting.
