### ISSUE TITLE
no documents in index after import

### ISSUE THREAD

**Issue by StefanNeuser** [ErickTamayo/laravel-scout-elastic#93]
Hi and thank you very much for the package!

i'm using elastic 6.1 with `"tamayo/laravel-scout-elastic": "^3.0",` at PHP 7.0.x running at ubuntu 16.04.

1. When i run import the index becomes not created (i created the index manuelly)
2. I created it manuelly and run the import again but no documents become imported

Here my config

```  
'driver' => env('SCOUT_DRIVER', 'elasticsearch'),

    'elasticsearch' => [
        'index' => env('ELASTICSEARCH_INDEX', 'moselmetzger'),
        'hosts' => [
            env('ELASTICSEARCH_HOST', 'http://localhost'),
        ],
    ],
    'queue' => env('SCOUT_QUEUE', false),
```

The Artisan Command

```
php artisan scout:import "App\Product"
Imported [App\Product] models up to ID: 12494
All [App\Product] records have been imported.
```

The Elastic index (i created the index manuelly)

```
curl -XGET 'localhost:9200/_cat/indices?v&pretty'
health status index           pri rep docs.count docs.deleted store.size pri.store.size 
yellow open   moselmetzger      5   1          0            0       795b           795b 
```

i'm not using the queue and queue-driver is also set to sync

I really need some help, thanks in advance

**Comment by StefanNeuser** [comment]
SOLVED, it just took some Time and theIndex was there... maybe somebody runs into the same issue.

**Comment by oguzcicek** [comment]
@StefanNeuser how did you solve the problem ? can you reindex the records ?
after`php artisan scout:import "App\Product"`
```
Imported [App\Models\BlogPost] models up to ID: 568
All [App\Models\BlogPost] records have been imported.
```
it shows like it's imported , but i can't get any result from index. when i check index , it looks empty.

**Comment by kronthto** [comment]
Sorry for reviving this old issue, I think someone wrote a comment and deleted it again, because it showed up "active" in my notifications...

I just want to add that a possible scenario for missing data in ES after importing is that ES import errors occur, but they are not escalated to notify you. It has been discussed here: 
- https://github.com/ErickTamayo/laravel-scout-elastic/issues/37
- https://github.com/elastic/elasticsearch/issues/25156


You can check this by dumping the response (result of `bulk` call) here: https://github.com/ErickTamayo/laravel-scout-elastic/blob/a8e5be767ba8d747d3a46c0b9805a25cfb9860d1/src/ElasticsearchEngine.php#L64
