### ISSUE TITLE
Incompatible with scout 4

### ISSUE THREAD

**Issue by IgorDePaula** [ErickTamayo/laravel-scout-elastic#95]
Incompatible with scout 4? Not install with laravel/scout 4

**Comment by kronthto** [comment]
I took a quick look at the changes in *laravel/scout v4* (https://github.com/laravel/scout/compare/3.0...4.0?w=1, didn't find a Changelog / Upgrading file sadly?) and it seems to boil down to:
* Drop PHP5 Support
* `saved` event rather than `created`&`updated`
* Whether or not to index an entity conditional by `shouldBeSearchable`
* Default sync behaviour I don't fully understand: https://github.com/laravel/scout/pull/264

IMHO nothing too bad, probably the only thing that is blocking right now is the constraint in *composer.json* (or did you get another error?): https://github.com/ErickTamayo/laravel-scout-elastic/blob/97deb01452f947b3c515545c2ee65804f1a59853/composer.json#L7 
Maybe it'll just work if we change it to `^3.0|^4.0`; I will do some tests on this if I find the time.

**Comment by IgorDePaula** [comment]
Seriuos? Only this? I do this, but is not the ideal.

**Comment by loranger** [comment]
Could we have an ETA, on this upgrade, please @ErickTamayo ?

**Comment by kronthto** [comment]
I did some more research and tests on this, with the conclusion that adjusting the version constraint is enough. See #99.

**Comment by ErickTamayo** [comment]
Closing due to age. a new version for Laravel 8 was released.
